wandb_version: 1

max_depth:
  desc: null
  value: 2
min_samples_leaf:
  desc: null
  value: 2
min_samples_split:
  desc: null
  value: 5
n_estimators:
  desc: null
  value: 45
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686074467.711119
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.16
      5: 0.15.3
      8:
      - 5
